### ISSUE TITLE
Link roto en el penúltimo paso de la instalación de Python

### ISSUE THREAD

**Issue by amarzar** [sdelquin/edubase#1]
En el penúltimo paso de la instalación de Python el enlace está roto. Entiendo que se debe a una reestructuración de los repositorios. "Buceando" por el repo **edubase** veo que el enlace correcto debería ser este:

https://raw.githubusercontent.com/sdelquin/edubase/main/docs/files/.mypy.ini

![SCR-20231119-und](https://github.com/sdelquin/edubase/assets/58997290/f6d88925-99d9-42c7-b621-e7bf42864d0f)

**Comment by sdelquin** [comment]
Muchas gracias @amarzar! La verdad es que al hacer la migración eso se me quedó atrás.
En cualquier caso he aprovechado para rehacer unas cuantas cosas. Lo mejor es que ahora obtengo la última versión estable de Python de manera programática, así el tutorial sirve para cualquier momento en el que se siga.

https://github.com/sdelquin/edubase/blob/main/docs/python-install.md
