### ISSUE TITLE
Link roto en la instalación de Python

### ISSUE THREAD

**Issue by amarzar** [sdelquin/edubase#2]
Al final de la guía de instalación de Python hay un enlace roto:

![SCR-20231129-oew](https://github.com/sdelquin/edubase/assets/58997290/c9da7397-8d44-43e7-8b29-c56c07948bcb)

Si no me equivoco el enlace correcto es: https://raw.githubusercontent.com/sdelquin/edubase/main/docs/files/.mypy.ini

**Comment by sdelquin** [comment]
Hola! Esto ya lo quité de la documentación. Quedó hecho en #1
